#!/bin/sh
# Regenerate ../clock_fonts.h from the DSEG TTFs (needs python3 with Pillow: pip install pillow).
# DSEG (c) Keshikan, SIL OFL 1.1 - fonts/DSEG-LICENSE.txt.
# The *-no7F.ttf files are DSEG7 Classic with segment F removed from the digit 7 (a real
# seven-segment "7"), produced from the stock TTFs by make_no7f.py (needs fontTools).
set -e
cd "$(dirname "$0")"
OUT=../clock_fonts.h
PY=${PYTHON:-python3}
cat > $OUT <<'HDR'
/* Digital-clock fonts for the ESP32-C3 OLED clock, U8g2 format.
 * Generated by tools/gen_fonts.sh - do not edit by hand.
 *
 *   font_dseg7_b_28   - DSEG7 Classic Bold 28 px, "0123456789: "    (HH:MM; space = digit width)
 *   font_dseg7_r_11   - DSEG7 Classic Regular 11 px, "0123456789-." (date, seconds, lunar date)
 *                       "." is given a 4 px cell (DSEG's decimal point has advance 0, it is meant
 *                       to overlay the digit)
 *   font_dseg14_r_11  - DSEG14 Classic Regular 11 px, "AMP"         (AM / PM)
 *
 * Upright faces, no shear: the slanted versions looked messy at these sizes on a 128x64 OLED.
 * (mkfont.py --shear is still available if you want to try again.)
 *
 * DSEG (c) Keshikan - SIL Open Font License 1.1 (tools/fonts/DSEG-LICENSE.txt)
 */
#ifndef CLOCK_FONTS_H
#define CLOCK_FONTS_H
#include <U8g2lib.h>

HDR
$PY mkfont.py --ttf fonts/DSEG7Classic-Bold-no7F.ttf    --size 28 --chars "0123456789: " --space-like 0 --name font_dseg7_b_28 --out $OUT --append
$PY mkfont.py --ttf fonts/DSEG7Classic-Regular-no7F.ttf --size 11 --chars "0123456789-." --adv .=4 --xoff .=1 --name font_dseg7_r_11 --out $OUT --append
$PY mkfont.py --ttf fonts/DSEG14Classic-Regular.ttf      --size 11 --chars "AMP"          --name font_dseg14_r_11 --out $OUT --append
echo '#endif /* CLOCK_FONTS_H */' >> $OUT
