#!/usr/bin/env python3
"""Rasterize a TTF subset with Pillow (FreeType) and emit a U8g2 font.

usage: mkfont.py --ttf FILE --size PX --chars "0123456789:" --name font_x [--thresh 128]
                 [--space-like CHAR] [--out file.h] [--preview]
"""
import argparse, sys
from PIL import Image, ImageDraw, ImageFont
import u8g2font as u8

def rasterize(ttf, size, chars, thresh=128, space_like=None):
    font = ImageFont.truetype(ttf, size)
    asc, desc = font.getmetrics()
    em = size
    glyphs = []
    for ch in chars:
        adv = font.getlength(ch)
        if ch == ' ' and space_like:
            adv = font.getlength(space_like)
        W = int(adv) + 3 * em; H = asc + desc + 2 * em
        im = Image.new('L', (W, H), 0)
        ImageDraw.Draw(im).text((em, em), ch, font=font, fill=255)
        px = im.load()
        rows = []
        for yy in range(H):
            rows.append([1 if px[xx, yy] >= thresh else 0 for xx in range(W)])
        ys = [yy for yy in range(H) if any(rows[yy])]
        if not ys:
            glyphs.append(u8.Glyph(ord(ch), 0, 0, 0, 0, round(adv), []))
            continue
        xs = [xx for xx in range(W) if any(rows[yy][xx] for yy in ys)]
        x0, x1, y0, y1 = min(xs), max(xs), min(ys), max(ys)
        bitmap = [rows[yy][x0:x1 + 1] for yy in range(y0, y1 + 1)]
        # baseline is at image y = em + asc
        base = em + asc
        g = u8.Glyph(ord(ch), x1 - x0 + 1, y1 - y0 + 1, x0 - em, base - (y1 + 1), round(adv), bitmap)
        glyphs.append(g)
    return glyphs

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--ttf', required=True); ap.add_argument('--size', type=int, required=True)
    ap.add_argument('--chars', required=True); ap.add_argument('--name', required=True)
    ap.add_argument('--thresh', type=int, default=128); ap.add_argument('--space-like', default=None)
    ap.add_argument('--out', default=None); ap.add_argument('--preview', action='store_true')
    ap.add_argument('--append', action='store_true')
    a = ap.parse_args()
    glyphs = rasterize(a.ttf, a.size, a.chars, a.thresh, a.space_like)
    data = u8.encode(glyphs)
    # round trip check
    hdr, back = u8.decode(data)
    for g in glyphs:
        b = back[g.enc]
        assert (g.w, g.h, g.x, g.y, g.d) == (b.w, b.h, b.x, b.y, b.d), (g.enc, g, b)
        assert g.bitmap == b.bitmap, f'bitmap mismatch for {chr(g.enc)}'
    vis = [g for g in glyphs if g.h]
    print(f'{a.name}: {len(data)} bytes, {len(glyphs)} glyphs, size={a.size} thresh={a.thresh} '
          f'top={max(g.top for g in vis)} bottom={min(g.y for g in vis)} '
          f'adv={[g.d for g in glyphs]}', file=sys.stderr)
    if a.preview:
        for g in glyphs:
            print(f'--- {chr(g.enc)!r} w={g.w} h={g.h} x={g.x} y={g.y} d={g.d}', file=sys.stderr)
            for row in g.bitmap:
                print(''.join('#' if p else '.' for p in row), file=sys.stderr)
    comment = (f'{a.name}: {a.ttf.split("/")[-1]} {a.size}px, chars "{a.chars}", thresh {a.thresh}'
               f' - generated by tools/mkfont.py')
    c = u8.to_c(a.name, data, comment)
    if a.out:
        with open(a.out, 'a' if a.append else 'w') as f:
            f.write(c + '\n')
    else:
        sys.stdout.write(c)

if __name__ == '__main__':
    main()
